app            = "wctg"
primary_region = "lhr"

[build]

[mounts]
  source      = "wctg_data"
  destination = "/data"

[env]
  DB_PATH = "/data/wctg.db"
  PORT    = "3000"

[http_service]
  internal_port       = 3000
  force_https         = true
  auto_stop_machines  = true
  auto_start_machines = true
  min_machines_running = 0
